system:
  env: local
alert:
  emergency_contacts: []
camera:
  resolution: [1280, 720]
  fps: 15
privacy:
  local_processing: true
  no_internet: true

api:
  base_url: http://localhost:4000
  ingest_token: dev-ingest-token


