name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Enforce npm@10
        run: |
          npm i -g npm@10
          npm --version

      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Install dependencies (workspaces)
        run: npm install --workspaces --include-workspace-root --no-audit --no-fund

      - name: Prisma generate
        run: npm run -w packages/db prisma:generate

      - name: Build db package
        run: npm run -w packages/db build

      - name: Build API
        run: npm run -w apps/api build

      - name: Build Web
        run: npm run -w apps/web build


