name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Ensure npm@10
        run: |
          npm i -g npm@10
          npm --version

      - name: Install (workspaces)
        run: npm ci --workspaces --include-workspace-root --no-audit --no-fund

      - name: Prisma generate
        run: npm run -w packages/db prisma:generate

      - name: Build shared db package
        run: npm run -w packages/db build

      - name: Typecheck API
        run: npx -w apps/api tsc -p tsconfig.json --noEmit

      - name: Build API
        run: npm run -w apps/api build

      - name: Build Web
        run: npm run -w apps/web build

      - name: Lint API
        run: npm run -w apps/api lint || true

      - name: Lint Web
        run: npm run -w apps/web lint || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Enterprise deps
        working-directory: apps/enterprise
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pytest

      - name: Run Enterprise tests
        working-directory: apps/enterprise
        env:
          PYTHONPATH: ${{ github.workspace }}
        shell: bash
        run: |
          set -e
          pytest -q || code=$?
          if [ "${code:-0}" -eq 5 ]; then
            echo "pytest: no tests collected (treating as success)"
            exit 0
          elif [ -n "${code:-}" ] && [ "$code" -ne 0 ]; then
            exit $code
          fi

      - name: Enterprise smoke test
        working-directory: apps/enterprise
        env:
          APP_ENV: test
          PORT: 5000
          API_URL: http://localhost:4000
          INGEST_TOKEN: dev-ingest-token
          YOLO_ENABLED: false
          FALL_ONNX_MODEL: ""
        run: |
          python -c "
          import requests
          import time
          import subprocess
          import sys
          import os
          
          # Start enterprise server
          proc = subprocess.Popen([sys.executable, '-m', 'uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '5000'], 
                                 stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
          time.sleep(5)
          
          try:
              # Test health endpoints
              base = 'http://localhost:5000'
              r = requests.get(f'{base}/api/health-status', timeout=5)
              assert r.status_code == 200, f'health-status: {r.status_code}'
              
              r = requests.get(f'{base}/api/system-status', timeout=5)
              assert r.status_code == 200, f'system-status: {r.status_code}'
              
              # Test toggles
              r = requests.get(f'{base}/api/toggles', timeout=5)
              assert r.status_code == 200, f'toggles GET: {r.status_code}'
              
              r = requests.post(f'{base}/api/toggles', json={'face_blur': True}, timeout=5)
              assert r.status_code == 200, f'toggles POST: {r.status_code}'
              
              # Test camera list
              r = requests.get(f'{base}/api/camera', timeout=5)
              assert r.status_code == 200, f'camera list: {r.status_code}'
              
              print('Enterprise smoke test: PASSED')
          finally:
              proc.terminate()
              proc.wait()
          "


