name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Ensure npm@10
        run: |
          npm i -g npm@10
          npm --version

      - name: Install (workspaces)
        run: npm ci --workspaces --include-workspace-root --no-audit --no-fund

      - name: Prisma generate
        run: npm run -w packages/db prisma:generate

      - name: Build shared db package
        run: npm run -w packages/db build

      - name: Typecheck API
        run: npx -w apps/api tsc -p apps/api/tsconfig.json --noEmit

      - name: Build API
        run: npm run -w apps/api build

      - name: Build Web
        run: npm run -w apps/web build

      - name: Lint API
        run: npm run -w apps/api lint || true

      - name: Lint Web
        run: npm run -w apps/web lint || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Enterprise deps
        working-directory: apps/enterprise
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pytest

      - name: Run Enterprise tests
        working-directory: apps/enterprise
        run: pytest -q


